In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import re
import pandas as pd

# Load CSV (replace 'input.csv' with your file path)
# Assuming the CSV has a column named 'text' that we want to clean
file = pd.read_excel("/content/Bhojpuri_combined (1).xlsx")
df = file['commentText']
df=pd.DataFrame(df)
df.head(10)

                                     commentText
0                    Patna me karwti Patna me❤❤❤
1                         बेशर्मी की हद हो गई है
2  ❤❤❤❤❤ very beautiful ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
3                               Beautifull video
4                 ❤❤beautiful✨❤✨❤✨❤✨ video❤❤❤❤❤❤
5                        Super jawab shot ❤❤❤❤❤❤
6                          बेशमीं की हद हो गई है
7                Sarm naam ki koi naam hota hain
8                                          Love
9              Sport nahi hota to bhitar ho jata

In [ ]:
import re
import pandas as pd


# Regex pattern for emojis/emoticons
EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons 😀-🙏
    "\U0001F300-\U0001F5FF"  # symbols & pictographs 🌍-💡
    "\U0001F680-\U0001F6FF"  # transport & map 🚀-🚦
    "\U0001F1E0-\U0001F1FF"  # flags 🇺🇸-🇮🇳
    "\U00002700-\U000027BF"  # dingbats ✨-➿
    "\U0001F900-\U0001F9FF"  # supplemental symbols 🤖-🦄
    "\U0001FA70-\U0001FAFF"  # extended pictographs 🛕-🧿
    "\u2764+"           # ❤ + variation selector ❤️
    "\u2665"
    "\u2764"
    "\U0001F5A4"
    "\u2764\uFE0F"# ♥ black heart suit
    "]+",
    flags=re.UNICODE
)

# Function to remove emojis from text
def remove_emojis(text):
    if pd.isna(text):  # handle missing values
        return "NULL "
    return EMOJI_PATTERN.sub(r'', str(text))

# Apply to the 'text' column (change if your column has a different name)
df["cleaned_text"] = df["commentText"].apply(remove_emojis)
df.head(25)

,commentText,cleaned_text
0,Patna me karwti Patna me❤❤❤,Patna me karwti Patna me
1,बेशर्मी की हद हो गई है,बेशर्मी की हद हो गई है
2,❤❤❤❤❤ very beautiful ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️,very beautiful
3,Beautifull video,Beautifull video
4,❤❤beautiful✨❤✨❤✨❤✨ video❤❤❤❤❤❤,beautiful video
5,Super jawab shot ❤❤❤❤❤❤,Super jawab shot
6,बेशमीं की हद हो गई है,बेशमीं की हद हो गई है
7,Sarm naam ki koi naam hota hain,Sarm naam ki koi naam hota hain
8,Love,Love
9,Sport nahi hota to bhitar ho jata,Sport nahi hota to bhitar ho jata
10,❤❤❤❤❤❤❤❤,
11,Bahut satik shot mara bhai ne super bhai❤❤❤❤❤❤...,Bahut satik shot mara bhai ne super bhai
12,Hii,Hii
13,Sidha dal Dena tha thnda ho jata eingen,Sidha dal Dena tha thnda ho jata eingen
14,भाई इस तरीका से धक्का क्यों,भाई इस तरीका से धक्का क्यों
15,हेलो ऐसा कोई वीडियो बनाता है क्या यार तुम लोग ...,हेलो ऐसा कोई वीडियो बनाता है क्या यार तुम लोग ...
16,Asa sort kitne log ne maar liya hai abhi tak s...,Asa sort kitne log ne maar liya hai abhi tak s...
17,कपडाउठाकेमारकयाकपडे़केउपरसेमार।रहाहैपेलदेअंदरतक,कपडाउठाकेमारकयाकपडे़केउपरसेमार।रहाहैपेलदेअंदरतक
18,Kitne rupe shot h,Kitne rupe shot h
19,Yah tumhare man baap ne Sanskar diye Hain tumhen,Yah tumhare man baap ne Sanskar diye Hain tumhen
20,Chandan.rajbhar.❤❤❤❤hii,Chandan.rajbhar.hii
21,Arey bhai tu to singal hadi hai bhabhi kitni m...,Arey bhai tu to singal hadi hai bhabhi kitni m...
22,Sharam Naam ki koi cheez nhi inlogo ke pass,Sharam Naam ki koi cheez nhi inlogo ke pass
23,Gana thik hai baki sab Ghatiyapan hai,Gana thik hai baki sab Ghatiyapan hai
24,Sala Mahoba badan mein jaane gane per dhakka,Sala Mahoba badan mein jaane gane per dhakka

In [ ]:
df['cleaned_text'] = df['cleaned_text'].apply(lambda x: re.sub(r'[,\\n]+', '', str(x)))
df['cleaned_text'] = df['cleaned_text'].apply(lambda x: re.sub(r'[.,"\n]+', ' ', str(x)).strip())
df['cleaned_text'].replace('', np.nan, inplace=True)
df.dropna(inplace=True,axis=0)
df.head(25)

/tmp/ipython-input-1707652214.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cleaned_text'].replace('', np.nan, inplace=True)

,commentText,cleaned_text
0,Patna me karwti Patna me❤❤❤,Pata me karwti Pata me
1,बेशर्मी की हद हो गई है,बेशर्मी की हद हो गई है
2,❤❤❤❤❤ very beautiful ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️,very beautiful
3,Beautifull video,Beautifull video
4,❤❤beautiful✨❤✨❤✨❤✨ video❤❤❤❤❤❤,beautiful video
5,Super jawab shot ❤❤❤❤❤❤,Super jawab shot
6,बेशमीं की हद हो गई है,बेशमीं की हद हो गई है
7,Sarm naam ki koi naam hota hain,Sarm aam ki koi aam hota hai
8,Love,Love
9,Sport nahi hota to bhitar ho jata,Sport ahi hota to bhitar ho jata
11,Bahut satik shot mara bhai ne super bhai❤❤❤❤❤❤...,Bahut satik shot mara bhai e super bhai
12,Hii,Hii
13,Sidha dal Dena tha thnda ho jata eingen,Sidha dal Dea tha thda ho jata eige
14,भाई इस तरीका से धक्का क्यों,भाई इस तरीका से धक्का क्यों
15,हेलो ऐसा कोई वीडियो बनाता है क्या यार तुम लोग ...,हेलो ऐसा कोई वीडियो बनाता है क्या यार तुम लोग ...
16,Asa sort kitne log ne maar liya hai abhi tak s...,Asa sort kite log e maar liya hai abhi tak sha...
17,कपडाउठाकेमारकयाकपडे़केउपरसेमार।रहाहैपेलदेअंदरतक,कपडाउठाकेमारकयाकपडे़केउपरसेमार।रहाहैपेलदेअंदरतक
18,Kitne rupe shot h,Kite rupe shot h
19,Yah tumhare man baap ne Sanskar diye Hain tumhen,Yah tumhare ma baap e Saskar diye Hai tumhe
20,Chandan.rajbhar.❤❤❤❤hii,Chada rajbhar hii
21,Arey bhai tu to singal hadi hai bhabhi kitni m...,Arey bhai tu to sigal hadi hai bhabhi kiti mot...
22,Sharam Naam ki koi cheez nhi inlogo ke pass,Sharam Naam ki koi cheez hi ilogo ke pass
23,Gana thik hai baki sab Ghatiyapan hai,Gaa thik hai baki sab Ghatiyapa hai
24,Sala Mahoba badan mein jaane gane per dhakka,Sala Mahoba bada mei jaae gae per dhakka
25,Pilva ke bad badhiya se pahle Babu,Pilva ke bad badhiya se pahle Babu

In [ ]:
# Save cleaned CSV
df['cleaned_text'].to_csv("cleaned_no_emojis.csv", index=False)
print("✅ Emoticons removed. Cleaned file saved as 'cleaned_no_emojis.csv'")
df.dropna(inplace=True)

✅ Emoticons removed. Cleaned file saved as 'cleaned_no_emojis.csv'